[package]
name = "website_stats"
version = "0.1.0"
edition = "2024"

[dependencies]
diesel = { version = "2.1.0", features = ["sqlite", "r2d2", "chrono"] }
rocket = { version = "0.5.1", features = ["json"] }
